/**********************************************************/
/**********************************************************/
/***************	Author: Adham Ibrahim	***************/
/***************	Layer: 	MCAL			***************/
/***************	SWC: 	Timer1			***************/
/***************	Version:1.00			***************/
/**********************************************************/
/**********************************************************/
#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "Timer1_private.h"
#include "Timer1_register.h"
#include "Timer1_config.h"
#include "Timer1_interface.h"


void(*INT)(void) = NULL; 

void Timer1_voidInit(void)
{
	/*Choose Timer Mode*/
	#if Timer1_MODE == NORMAL
	CLR_BIT(TCCR1A,TCCR1A_WGM10);
	CLR_BIT(TCCR1A,TCCR1A_WGM11);
	CLR_BIT(TCCR1B,TCCR1B_WGM12);
	CLR_BIT(TCCR1B,TCCR1B_WGM13);
	
	#elif Timer1_MODE == PHASE_CORRECT8
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	CLR_BIT(TCCR1A,TCCR1A_WGM11);
	CLR_BIT(TCCR1B,TCCR1B_WGM12);
	CLR_BIT(TCCR1B,TCCR1B_WGM13);
	
	#elif Timer1_MODE == PHASE_CORRECT9
	CLR_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	CLR_BIT(TCCR1B,TCCR1B_WGM12);
	CLR_BIT(TCCR1B,TCCR1B_WGM13);
	
	#elif Timer1_MODE == PHASE_CORRECT10
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	CLR_BIT(TCCR1B,TCCR1B_WGM12);
	CLR_BIT(TCCR1B,TCCR1B_WGM13);
	
	#elif Timer1_MODE == CTC_OCR1A
	CLR_BIT(TCCR1A,TCCR1A_WGM10);
	CLR_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	CLR_BIT(TCCR1B,TCCR1B_WGM13);
	
	#elif Timer1_MODE == FAST_PWM8
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	CLR_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	CLR_BIT(TCCR1B,TCCR1B_WGM13);
	
	#elif Timer1_MODE == FAST_PWM9
	CLR_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	CLR_BIT(TCCR1B,TCCR1B_WGM13);
	
	#elif Timer1_MODE == FAST_PWM10
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	CLR_BIT(TCCR1B,TCCR1B_WGM13);
	
	#elif Timer1_MODE == PHASE_CORRECT_ICR1
	CLR_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	CLR_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);
	
	#elif Timer1_MODE == PHASE_CORRECT_OCR1A
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	CLR_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);
	
	#elif Timer1_MODE == CTC_ICR1
	CLR_BIT(TCCR1A,TCCR1A_WGM10);
	CLR_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);
	
	#elif Timer1_MODE == FAST_PWM_ICR1
	CLR_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);
	
	#elif Timer1_MODE == CTC_OCR1A
	SET_BIT(TCCR1A,TCCR1A_WGM10);
	SET_BIT(TCCR1A,TCCR1A_WGM11);
	SET_BIT(TCCR1B,TCCR1B_WGM12);
	SET_BIT(TCCR1B,TCCR1B_WGM13);	
	#endif
		
	/*Select PreScaler*/
	TCCR1B &= Timer1_PRESCALER_MASK;
	TCCR1B |= Timer1_PRESCALLER;
	
	/*Clear Registers*/
	TCNT1 = 0;
	OCR1A = 0;
	ICR1 = 0;
	
	/*Disable Interrupts*/
	CLR_BIT(TIMSK,TIMSK_TOIE1);
	CLR_BIT(TIMSK,TIMSK_OCIE1A);
	CLR_BIT(TIMSK,TIMSK_OCIE1B);
	CLR_BIT(TIMSK,TIMSK_TICIE1);
	
	/*Disable Flags*/
	SET_BIT(TIFR,TIFR_TOV1);
	SET_BIT(TIFR,TIFR_OCF1B);
	SET_BIT(TIFR,TIFR_OCF1A);
	SET_BIT(TIFR,TIFR_ICF1);	
}

void Timer1_SetCompareMatchMode(void)
{
	#if COMPARE_MODE == NON_PWM_NORMAL
	CLR_BIT(TCCR1A,TCCR1A_COM1A0);
	CLR_BIT(TCCR1A,TCCR1A_COM1A1);
	
	#elif COMPARE_MODE == NON_PWM_TOGGLE
	SET_BIT(TCCR1A,TCCR1A_COM1A0);
	CLR_BIT(TCCR1A,TCCR1A_COM1A1);
	
	#elif COMPARE_MODE == NON_PWM_SET
	CLR_BIT(TCCR1A,TCCR1A_COM1A0);
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	
	#elif COMPARE_MODE == NON_PWM_CLEAR
	SET_BIT(TCCR1A,TCCR1A_COM1A0);
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	
	#elif COMPARE_MODE == FAST_PWM_NORMAL
	CLR_BIT(TCCR1A,TCCR1A_COM1A0);
	CLR_BIT(TCCR1A,TCCR1A_COM1A1);
	
	#elif COMPARE_MODE == FAST_PWM_TOGGLE
	SET_BIT(TCCR1A,TCCR1A_COM1A0);
	CLR_BIT(TCCR1A,TCCR1A_COM1A1);
	
	#elif COMPARE_MODE == FAST_PWM_NONINV
	CLR_BIT(TCCR1A,TCCR1A_COM1A0);
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	
	#elif COMPARE_MODE == FAST_PWM_INV
	SET_BIT(TCCR1A,TCCR1A_COM1A0);
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	
	#elif COMPARE_MODE == PHASE_CORRECT_NORMAL
	CLR_BIT(TCCR1A,TCCR1A_COM1A0);
	CLR_BIT(TCCR1A,TCCR1A_COM1A1);
	
	#elif COMPARE_MODE == PHASE_CORRECT_TOGGLE
	SET_BIT(TCCR1A,TCCR1A_COM1A0);
	CLR_BIT(TCCR1A,TCCR1A_COM1A1);
	
	#elif COMPARE_MODE == PHASE_CORRECT_NONINV
	CLR_BIT(TCCR1A,TCCR1A_COM1A0);
	SET_BIT(TCCR1A,TCCR1A_COM1A1);
	
	#elif COMPARE_MODE == PHASE_CORRECT_INV
	SET_BIT(TCCR1A,TCCR1A_COM1A0);
	SET_BIT(TCCR1A,TCCR1A_COM1A1);	
	#endif
}

void Timer1_ICUInterruptEnable(void)
{
	SET_BIT(TIMSK,TIMSK_TICIE1);
}

void Timer1_ICUInterruptDisable(void)
{
	CLR_BIT(TIMSK,TIMSK_TICIE1);
}

void Timer1_ICUSenseMode (u8 Mode)
{
	/*Falling Edge*/
	if (Mode == ICU_FALLING_EDGE)
	{
		CLR_BIT(TCCR1B,TCCR1B_ICES1);
	}
	
	/*Rising Edge*/
	else if(Mode == ICU_RISING_EDGE)
	{
		SET_BIT(TCCR1B,TCCR1B_ICES1);
	}
}

u16 Timer1_ICR1Read(void)
{
	return ICR1;
}

void Timer1_voidSetOCR1AValue(u16 Value)
{
	OCR1A = Value;
}

void Timer1_voidSetICR1Value(u16 Value)
{
	ICR1 = Value;
}

void Timer1_VoidICUSetCallBack(void (*Copy_pf) (void))
{
	INT = Copy_pf;
}

void __vector_6(void) __attribute__((signal));
void __vector_6(void)
{
	INT();
}